[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = """
      default-src 'self';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com;
      connect-src 'self' https://api.quran.com https://api.aladhan.com https://cdn.jsdelivr.net https://fonts.googleapis.com https://almotqenapi.onrender.com;
      font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      img-src 'self' data:;
    """
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
